apiVersion: v1
kind: Namespace
metadata:
  name: test-namespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: test-namespace
  name: nginx_admin
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["services", "configmaps"]
  verbs: ["create", "watch", "list", "get", "update", "patch"]
- apiGroups: ["apps"] 
  resources: ["deployments"]
  verbs: ["create", "watch", "list", "get", "update", "patch"]
- apiGroups: ["cert-manager.io"] 
  resources: ["issuers"]
  verbs: ["create", "watch", "list", "get", "update", "patch"]
- apiGroups: ["networking.k8s.io"] 
  resources: ["ingresses"]
  verbs: ["create", "watch", "list", "get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "jane" to read pods in the "default" namespace.
# You need to already have a Role named "pod-reader" in that namespace.
kind: RoleBinding
metadata:
  name: nginx_admin_rolebinding
  namespace: test-namespace
subjects:
# You can specify more than one "subject"
- kind: User
  name: ruslan # "name" is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: Role #this must be Role or ClusterRole
  name: nginx_admin # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
